import { GameDificultness } from "@prisma/client";
import { prisma } from "../..";

export const games = async () => await prisma.game.createMany({
    data: [
      {
        id: 1,
        title: 'Dobrodružná Výprava',
        slug: "dobrodruzna-vyzva",
        description: 'Napínavé dobrodružství čeká!',
        place: 'Praha',
        dificultness: GameDificultness.NORMAL,
        startingCheckpointId: 1,
        endingCheckpointId: 5,
        authorId: 3,
        isActive: true,
        price: 299,
        maxPoints: 1000,
        imageId: 4,
      },
      {
        id: 2,
        title: 'Úniková Výzva',
        slug: "unikova-vyzva",
        description: 'Dokážete uniknout včas?',
        place: 'Brno',
        dificultness: GameDificultness.HARD,
        startingCheckpointId: 1,
        endingCheckpointId: 3,
        authorId: 2,
        isActive: true,
        price: 399,
        maxPoints: 1500,
        imageId: 5,
      },
      {
        id: 3,
        title: 'Záhada Olomouce',
        slug: "zahada-olomouce",
        description: 'Vyřešte záhady Olomouce!',
        place: 'Olomouc',
        dificultness: GameDificultness.EASY,
        startingCheckpointId: 6,
        endingCheckpointId: 10,
        authorId: 4,
        isActive: true,
        price: 199,
        maxPoints: 800,
        imageId: 15,
      },
      {
        id: 4,
        title: 'Únik ze Strašidelného Domu',
        slug: "unik-ze-strasidelneho-domu",
        description: 'Únik z strašidelného domu!',
        place: 'Plzeň',
        dificultness: GameDificultness.NORMAL,
        startingCheckpointId: 11,
        endingCheckpointId: 15,
        authorId: 3,
        isActive: true,
        price: 299,
        maxPoints: 1200,
        imageId: 7,
      },
      {
        id: 5,
        title: 'Hon za Pokladem',
        slug: "hon-za-pokladem",
        description: 'Najděte skrytý poklad!',
        place: 'Český Krumlov',
        dificultness: GameDificultness.NORMAL,
        startingCheckpointId: 16,
        endingCheckpointId: 20,
        authorId: 5,
        isActive: true,
        price: 249,
        maxPoints: 1000,
        imageId: 8,
      },
      {
        id: 6,
        title: 'Tajemství Staré Prahy',
        slug: "tajemstvi-stare-prahy",
        description: 'Objevte tajemství Staré Prahy!',
        place: 'Praha',
        dificultness: GameDificultness.HARD,
        startingCheckpointId: 21,
        endingCheckpointId: 25,
        authorId: 6,
        isActive: true,
        price: 349,
        maxPoints: 1500,
        imageId: 9,
      },
      {
        id: 7,
        title: 'Záhada Brněnského Podzemí',
        slug: "zahada-brnenskeho-podzemi",
        description: 'Prozkoumejte brněnské podzemí!',
        place: 'Brno',
        dificultness: GameDificultness.NORMAL,
        startingCheckpointId: 26,
        endingCheckpointId: 30,
        authorId: 7,
        isActive: true,
        price: 299,
        maxPoints: 1200,
        imageId: 10,
      },
      {
        id: 8,
        title: 'Dobrodružství v Plzni',
        slug: "dobrodruzstvi-v-plzni",
        description: 'Zažijte dobrodružství v Plzni!',
        place: 'Plzeň',
        dificultness: GameDificultness.EASY,
        startingCheckpointId: 31,
        endingCheckpointId: 35,
        authorId: 8,
        isActive: true,
        price: 199,
        maxPoints: 800,
        imageId: 11,
      },
      {
        id: 9,
        title: 'Záhada Českého Krumlova',
        slug: "zahada-ceskeho-krumlova",
        description: 'Odhalte záhady Českého Krumlova!',
        place: 'Český Krumlov',
        dificultness: GameDificultness.HARD,
        startingCheckpointId: 36,
        endingCheckpointId: 40,
        authorId: 9,
        isActive: true,
        price: 399,
        maxPoints: 1500,
        imageId: 12,
      },
      {
        id: 10,
        title: 'Olomoucké Dobrodružství',
        slug: "olomoucke-dobrodruzstvi",
        description: 'Zažijte dobrodružství v Olomouci!',
        place: 'Olomouc',
        dificultness: GameDificultness.NORMAL,
        startingCheckpointId: 41,
        endingCheckpointId: 45,
        authorId: 10,
        isActive: true,
        price: 299,
        maxPoints: 1200,
        imageId: 13,
      },
    ],
  });
