import { prisma } from '../../'

export const files = async () =>
  await prisma.file.createMany({
    data: [
      {
        id: 1,
        generatedName: 'file1.jpg',
        originalName: 'original1.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 2,
        generatedName: 'file2.png',
        originalName: 'original2.png',
        path: '/uploads/images/file2.png',
      },
      {
        id: 3,
        generatedName: 'file3.png',
        originalName: 'original3.png',
        path: '/uploads/images/file3.png',
      },
      {
        id: 4,
        generatedName: 'file4.png',
        originalName: 'original4.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 5,
        generatedName: 'file5.png',
        originalName: 'original5.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 6,
        generatedName: 'file6.pdf',
        originalName: 'original6.pdf',
        path: '/uploads/contracts/file6.pdf',
      },
      {
        id: 7,
        generatedName: 'file7.png',
        originalName: 'original7.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 8,
        generatedName: 'file8.png',
        originalName: 'original8.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 9,
        generatedName: 'file9.png',
        originalName: 'original9.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 10,
        generatedName: 'file10.png',
        originalName: 'original10.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 11,
        generatedName: 'file11.png',
        originalName: 'original11.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 12,
        generatedName: 'file12.png',
        originalName: 'original12.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 13,
        generatedName: 'file13.png',
        originalName: 'original13.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 14,
        generatedName: 'file14.pdf',
        originalName: 'original14.pdf',
        path: '/uploads/contracts/file14.pdf',
      },
      {
        id: 15,
        generatedName: 'file15.png',
        originalName: 'original15.png',
        path: '/uploads/images/file7.png',
      },
      {
        id: 16,
        generatedName: 'file16.png',
        originalName: 'original16.png',
        path: '/uploads/documents/file16.png',
      },
      {
        id: 17,
        generatedName: 'file17.png',
        originalName: 'original17.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 18,
        generatedName: 'file18.jpg',
        originalName: 'original18.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 19,
        generatedName: 'file19.png',
        originalName: 'original19.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 20,
        generatedName: 'file20.jpg',
        originalName: 'original20.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 21,
        generatedName: 'file21.png',
        originalName: 'original21.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 22,
        generatedName: 'file22.jpg',
        originalName: 'original22.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 23,
        generatedName: 'file23.png',
        originalName: 'original23.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 24,
        generatedName: 'file24.jpg',
        originalName: 'original24.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 25,
        generatedName: 'file25.png',
        originalName: 'original25.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 26,
        generatedName: 'file26.jpg',
        originalName: 'original26.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 27,
        generatedName: 'file27.png',
        originalName: 'original27.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 28,
        generatedName: 'file28.jpg',
        originalName: 'original28.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 29,
        generatedName: 'file29.png',
        originalName: 'original29.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 30,
        generatedName: 'file30.jpg',
        originalName: 'original30.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 31,
        generatedName: 'file31.png',
        originalName: 'original31.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 32,
        generatedName: 'file32.jpg',
        originalName: 'original32.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 33,
        generatedName: 'file33.png',
        originalName: 'original33.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 34,
        generatedName: 'file34.jpg',
        originalName: 'original34.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 35,
        generatedName: 'file35.png',
        originalName: 'original35.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 36,
        generatedName: 'file36.jpg',
        originalName: 'original36.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 37,
        generatedName: 'file37.png',
        originalName: 'original37.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 38,
        generatedName: 'file38.jpg',
        originalName: 'original38.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 39,
        generatedName: 'file39.png',
        originalName: 'original39.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 40,
        generatedName: 'file40.jpg',
        originalName: 'original40.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 41,
        generatedName: 'file41.png',
        originalName: 'original41.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 42,
        generatedName: 'file42.jpg',
        originalName: 'original42.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 43,
        generatedName: 'file43.png',
        originalName: 'original43.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 44,
        generatedName: 'file44.jpg',
        originalName: 'original44.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 45,
        generatedName: 'file45.png',
        originalName: 'original45.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 46,
        generatedName: 'file46.jpg',
        originalName: 'original46.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 47,
        generatedName: 'file47.png',
        originalName: 'original47.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 48,
        generatedName: 'file48.jpg',
        originalName: 'original48.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 49,
        generatedName: 'file49.png',
        originalName: 'original49.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 50,
        generatedName: 'file50.jpg',
        originalName: 'original50.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 51,
        generatedName: 'file51.png',
        originalName: 'original51.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 52,
        generatedName: 'file52.jpg',
        originalName: 'original52.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 53,
        generatedName: 'file53.png',
        originalName: 'original53.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 54,
        generatedName: 'file54.jpg',
        originalName: 'original54.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 55,
        generatedName: 'file55.png',
        originalName: 'original55.png',
        path: '/uploads/images/file5.png',
      },
      {
        id: 56,
        generatedName: 'file56.jpg',
        originalName: 'original56.jpg',
        path: '/uploads/images/file1.jpg',
      },
      {
        id: 57,
        generatedName: 'file57.png',
        originalName: 'original57.png',
        path: '/uploads/images/file5.png',
      },
    ],
  })
